language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.8.2"
  - DJANGO="django==1.7.4"
  - DJANGO="django==1.6.10"
  - DJANGO="django==1.5.12"
  - DJANGO="django==1.4.19"

install:
  - pip install $DJANGO
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install pillow==1.7.8; fi"
  - export PYTHONPATH=.
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - django-admin.py startproject deepzoom_test && coverage run --source='deepzoom' --omit='deepzoom/admin.py' deepzoom_test/manage.py test deepzoom --settings=deepzoom.test.test_settings

after_success:
  coveralls

matrix:
  fast_finish: true
  exclude:
    - python: "2.6"
      env: DJANGO="django==1.7.4"
    - python: "2.6"
      env: DJANGO="django==1.8.2"
    - python: "2.7"
      env: DJANGO="django==1.7.4"
    - python: "2.7"
      env: DJANGO="django==1.8.2"
    - python: "3.2"
      env: DJANGO="django==1.4.19"
    - python: "3.3"
      env: DJANGO="django==1.4.19"
    - python: "3.4"
      env: DJANGO="django==1.4.19"
