language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.7.4 --use-mirrors"
  - DJANGO="django==1.6.10 --use-mirrors"
  - DJANGO="django==1.5.12 --use-mirrors"
  - DJANGO="django==1.4.19 --use-mirrors"

install:
  - pip install $DJANGO
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install pillow==1.7.8 --use-mirrors; fi"
  - export PYTHONPATH=.
  - pip install -r requirements.txt --use-mirrors

script:
  - django-admin.py startproject deepzoom_test && python deepzoom_test/manage.py test deepzoom --settings=deepzoom.test.test_settings

matrix:
  fast_finish: true
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.19 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.4.19 --use-mirrors"
    - python: "3.4"
      env: DJANGO="django==1.4.19 --use-mirrors"
